### ISSUE TITLE
Edge does not support matchAll

### ISSUE THREAD

**Issue by crobibero** [kakaroto/fvtt-module-trigger-happy#2]
tested with 

```
const regexp = RegExp('foo[a-z]*','g');
const str = 'table football, foosball';
const matches = str.matchAll(regexp);
```

![image](https://user-images.githubusercontent.com/24963659/78453418-cbfb6b80-764e-11ea-9525-37882b5d17c5.png)

**Comment by kakaroto** [comment]
According to this, it does since v79 (which was released in January, according to wikipedia and seems to be the first chromium based version of edge)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll

I've been lookging at polyfill for matchAll in order to try and include it somehow but it seems overly complicated to support an old version of a browser that most people don't use (and shouldn't use).

There's two alternative possibilities of doing a 'g' regexp match with capturing groups, and they are explained in the proposal for matchAll : https://github.com/tc39/proposal-string-matchall

Note however that Foundry itself uses the same matchAll to find all the entity links in the journal entry, so that would still crash I think.

**Comment by kakaroto** [comment]
Closing since I have no intentions of using an alternative to matchAll considering that Foundry itself uses it already, so links in journals are already broken in Edge, and a new version of Edge supports it.
